site_title: Will K's Feed
favicon: /assets/uploads/favicon.png
header_bio: Will Karmis is a sound artist that makes sound sometimes with music
  and guitar while sitting on a computer and think up ways to make sound while
  also trying to write a family size open for awesomeness I am drinking coffee
  right now.
information: >-
  Chicago, IL\

  willkarmis@gmail.com


  CV


  [Hendi Dolupta Tioreicatur Autemqui](https://pedantic-stonebraker-819757.netlify.app/)\

  December 2019


  Ut Fugit Lanto Blant Volupta Quis\

  August 2019


  Hendi Dolupta Tioreicatur Autemqui\

  December 2019


  Ut Fugit Lanto Blant Volupta Quis\

  August 2019


  Hendi Dolupta Tioreicatur Autemqui\

  December 2019


  Ut Fugit Lanto Blant Volupta Quis\

  August 2019
footer: Test test © Will Karmis, 2021
