backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'
site_url: https://wks-feed.netlify.app/

collections:
  - name: 'feed'
    label: 'Will K’s Feed'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Slug', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'General'
        file: '_data/settings.yml'
        fields:
          - { label: 'Site Title (for browser tab)', name: 'site_title', widget: 'string' }
          - { label: 'Favicon', name: 'favicon', widget: 'image', required: false }
          - { label: 'Header Bio', name: 'header_bio', widget: 'markdown' }
          - { label: 'Information', name: 'information', widget: 'markdown' }
          - { label: 'Footer', name: 'footer', widget: 'string' }